"""
HenkerDPI - Language Support
8 languages. General-purpose DPI bypass.
"""

import json
import os

from config import STATE_DIR, resolve_pref

# Preferences live in the per-user state dir (see config.state_dir): a frozen
# build's __file__ resolves inside the ephemeral _MEIxxxx temp dir Windows
# deletes on exit, so writing there would silently reset the UI language to
# English on every launch.
LANG_DIR = STATE_DIR
LANG_FILE = resolve_pref("lang_pref.json")

LANGUAGES = {
    "tr": {
        "name": "Türkçe",
        "badge_offline": "  Çevrimdışı  ",
        "badge_online": "  Çevrimiçi  ",
        "status_off": "Bypass Kapalı",
        "status_on": "Koruma Aktif",
        "desc_off": "Başlatmak için butona tıklayın",
        "desc_on": "DPI bypass çalışıyor",
        "stat_bypass": "Bypass",
        "stat_passed": "Geçen",
        "stat_uptime": "Süre",
        "info_method": "Yöntem",
        "info_fragment": "Parçalama",
        "log": "Günlük",
        "clear": "Temizle",
        "autostart": "Açılışta başlat",
        "tray_show": "Göster",
        "tray_start": "Başlat",
        "tray_stop": "Durdur",
        "tray_quit": "Çıkış",
        "close_confirm": "Bypass çalışıyor. Kapatılsın mı?",
        "already_running": "HenkerDPI zaten çalışıyor!",
        "admin_required": "Yönetici yetkisi gerekli!\nSağ tık > Yönetici olarak çalıştır",
        "autostart_added": "[+] Açılışa eklendi",
        "autostart_removed": "[-] Açılıştan kaldırıldı",
        "autostart_unsupported": "[!] macOS'ta açılışta başlatma desteklenmiyor",
        "engine_active": "[+] HenkerDPI aktif",
        "engine_stopped": "[-] Durduruldu",
        "uptime_fmt": "{h}s {m}dk",
        "uptime_fmt_short": "{m}dk {s}sn",
        "log_block": "Engel",
        "custom_domains": "Özel Alan Adları",
        "add_domain": "Ekle",
        "remove_domain": "Sil",
        "domain_placeholder": "örn: youtube.com",
        "domain_added": "[+] Alan adı eklendi: {domain}",
        "domain_removed": "[-] Alan adı silindi: {domain}",
        "domain_exists": "[!] Alan adı zaten listede: {domain}",
        "domain_invalid": "[!] Geçersiz alan adı",
        "mode_all": "Tümü",
        "mode_selective": "Seçili",
        "mode_label": "Bypass Modu",
        "categories": "Kategoriler",
        "doh_label": "Güvenli DNS",
        "doh_desc": "Engellemeyi aşmak için DNS sunucusunu değiştirir (şifreli değil)",
        "update_available": "v{version} çıktı",
        "update_button": "Güncelle",
        "update_notes": "Neler değişti?",
        "update_downloading": "İndiriliyor... %{pct}",
        "update_verifying": "Doğrulanıyor...",
        "update_stopping": "Motor durduruluyor...",
        "update_restarting": "Yeniden başlatılıyor...",
        "update_failed": "Güncelleme başarısız",
        "update_none": "[*] En güncel sürümü kullanıyorsunuz",
    },
    "en": {
        "name": "English",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running — all traffic protected",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close it?",
        "already_running": "HenkerDPI is already running!",
        "admin_required": "Admin privileges required!\nRight click > Run as administrator",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "autostart_unsupported": "[!] Start-at-login is not supported on macOS",
        "engine_active": "[+] HenkerDPI active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Switch resolver to bypass DNS blocking (not encrypted)",
        "update_available": "Version {version} is available",
        "update_button": "Update",
        "update_notes": "What's new?",
        "update_downloading": "Downloading... {pct}%",
        "update_verifying": "Verifying...",
        "update_stopping": "Stopping the engine...",
        "update_restarting": "Restarting...",
        "update_failed": "Update failed",
        "update_none": "[*] You are on the latest version",
    },
    "hi": {
        "name": "Hindi",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Start button press kare",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!\nRight click > Run as administrator",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "autostart_unsupported": "[!] macOS पर लॉगिन पर स्वतः शुरू करना समर्थित नहीं है",
        "engine_active": "[+] HenkerDPI active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Switch resolver to bypass DNS blocking (not encrypted)",
        "update_available": "Version {version} is available",
        "update_button": "Update",
        "update_notes": "What's new?",
        "update_downloading": "Downloading... {pct}%",
        "update_verifying": "Verifying...",
        "update_stopping": "Stopping the engine...",
        "update_restarting": "Restarting...",
        "update_failed": "Update failed",
        "update_none": "[*] You are on the latest version",
    },
    "ja": {
        "name": "Japanese",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "autostart_unsupported": "[!] macOS ではログイン時の自動起動に対応していません",
        "engine_active": "[+] HenkerDPI active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Switch resolver to bypass DNS blocking (not encrypted)",
        "update_available": "Version {version} is available",
        "update_button": "Update",
        "update_notes": "What's new?",
        "update_downloading": "Downloading... {pct}%",
        "update_verifying": "Verifying...",
        "update_stopping": "Stopping the engine...",
        "update_restarting": "Restarting...",
        "update_failed": "Update failed",
        "update_none": "[*] You are on the latest version",
    },
    "zh": {
        "name": "Chinese",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "autostart_unsupported": "[!] macOS 不支持开机自动启动",
        "engine_active": "[+] HenkerDPI active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Switch resolver to bypass DNS blocking (not encrypted)",
        "update_available": "Version {version} is available",
        "update_button": "Update",
        "update_notes": "What's new?",
        "update_downloading": "Downloading... {pct}%",
        "update_verifying": "Verifying...",
        "update_stopping": "Stopping the engine...",
        "update_restarting": "Restarting...",
        "update_failed": "Update failed",
        "update_none": "[*] You are on the latest version",
    },
    "ru": {
        "name": "Russian",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Autostart",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "autostart_unsupported": "[!] Автозапуск не поддерживается в macOS",
        "engine_active": "[+] HenkerDPI active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Switch resolver to bypass DNS blocking (not encrypted)",
        "update_available": "Доступна версия {version}",
        "update_button": "Обновить",
        "update_notes": "Что нового?",
        "update_downloading": "Загрузка... {pct}%",
        "update_verifying": "Проверка...",
        "update_stopping": "Остановка движка...",
        "update_restarting": "Перезапуск...",
        "update_failed": "Ошибка обновления",
        "update_none": "[*] У вас последняя версия",
    },
    "de": {
        "name": "Deutsch",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Aus",
        "status_on": "Schutz Aktiv",
        "desc_off": "Klicken Sie zum Starten",
        "desc_on": "DPI Bypass aktiv",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Methode",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Autostart",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "autostart_unsupported": "[!] Autostart wird unter macOS nicht unterstützt",
        "engine_active": "[+] HenkerDPI active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Switch resolver to bypass DNS blocking (not encrypted)",
        "update_available": "Version {version} ist verfügbar",
        "update_button": "Aktualisieren",
        "update_notes": "Was ist neu?",
        "update_downloading": "Wird geladen... {pct}%",
        "update_verifying": "Wird geprüft...",
        "update_stopping": "Engine wird gestoppt...",
        "update_restarting": "Neustart...",
        "update_failed": "Update fehlgeschlagen",
        "update_none": "[*] Sie nutzen die neueste Version",
    },
    "da": {
        "name": "Dansk",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "autostart_unsupported": "[!] Start ved login understøttes ikke på macOS",
        "engine_active": "[+] HenkerDPI active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Switch resolver to bypass DNS blocking (not encrypted)",
        "update_available": "Version {version} is available",
        "update_button": "Update",
        "update_notes": "What's new?",
        "update_downloading": "Downloading... {pct}%",
        "update_verifying": "Verifying...",
        "update_stopping": "Stopping the engine...",
        "update_restarting": "Restarting...",
        "update_failed": "Update failed",
        "update_none": "[*] You are on the latest version",
    },
}

DEFAULT_LANG = "en"


def load_lang_pref() -> str:
    try:
        with open(LANG_FILE, "r") as f:
            data = json.load(f)
            lang = data.get("lang", DEFAULT_LANG)
            if lang in LANGUAGES:
                return lang
    except Exception:
        pass
    return DEFAULT_LANG


def save_lang_pref(lang: str):
    with open(LANG_FILE, "w") as f:
        json.dump({"lang": lang}, f)


def t(key: str, lang: str = None, **kwargs) -> str:
    if lang is None:
        lang = load_lang_pref()
    text = LANGUAGES.get(lang, LANGUAGES[DEFAULT_LANG]).get(key, key)
    if kwargs:
        text = text.format(**kwargs)
    return text
