"""
HenkerDPI V2 - Language Support
9 dil — Discord referansları kaldırıldı, genel amaçlı.
"""

import json
import os

LANG_DIR = os.path.dirname(os.path.abspath(__file__))
LANG_FILE = os.path.join(LANG_DIR, "lang_pref.json")

LANGUAGES = {
    "tr": {
        "name": "Türkçe",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Kapalı",
        "status_on": "Koruma Aktif",
        "desc_off": "Başlatmak için butona tıklayın",
        "desc_on": "DPI bypass çalışıyor — tüm trafik korunuyor",
        "stat_bypass": "Bypass",
        "stat_passed": "Geçen",
        "stat_uptime": "Süre",
        "info_method": "Yöntem",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Temizle",
        "autostart": "Açılışta başlat",
        "tray_show": "Göster",
        "tray_start": "Başlat",
        "tray_stop": "Durdur",
        "tray_quit": "Çıkış",
        "close_confirm": "Bypass çalışıyor. Kapatılsın mı?",
        "already_running": "HenkerDPI zaten çalışıyor!",
        "admin_required": "Yönetici yetkisi gerekli!\nSağ tık > Yönetici olarak çalıştır",
        "autostart_added": "[+] Açılışa eklendi",
        "autostart_removed": "[-] Açılıştan kaldırıldı",
        "engine_active": "[+] HenkerDPI V2 aktif",
        "engine_stopped": "[-] Durduruldu",
        "uptime_fmt": "{h}s {m}dk",
        "uptime_fmt_short": "{m}dk {s}sn",
        "log_block": "Engel",
        "custom_domains": "Özel Domainler",
        "add_domain": "Ekle",
        "remove_domain": "Sil",
        "domain_placeholder": "örn: youtube.com",
        "domain_added": "[+] Domain eklendi: {domain}",
        "domain_removed": "[-] Domain silindi: {domain}",
        "domain_exists": "[!] Domain zaten listede: {domain}",
        "domain_invalid": "[!] Geçersiz domain",
        "mode_all": "Tümü",
        "mode_selective": "Seçili",
        "mode_label": "Bypass Modu",
        "categories": "Kategoriler",
        "doh_label": "Güvenli DNS",
        "doh_desc": "DNS-over-HTTPS ile DNS engellemesini aş",
    },
    "en": {
        "name": "English",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running — all traffic protected",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close it?",
        "already_running": "HenkerDPI is already running!",
        "admin_required": "Admin privileges required!\nRight click > Run as administrator",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "engine_active": "[+] HenkerDPI V2 active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Bypass DNS blocking with DNS-over-HTTPS",
    },
    "hi": {
        "name": "हिन्दी",
        "badge_offline": "  ऑफ़लाइन  ",
        "badge_online": "  ऑनलाइन  ",
        "status_off": "बायपास बंद",
        "status_on": "सुरक्षा सक्रिय",
        "desc_off": "शुरू करने के लिए बटन दबाएं",
        "desc_on": "DPI बायपास चल रहा है — सभी ट्रैफ़िक सुरक्षित",
        "stat_bypass": "बायपास",
        "stat_passed": "पास",
        "stat_uptime": "समय",
        "info_method": "तरीका",
        "info_fragment": "Fragment",
        "log": "लॉग",
        "clear": "साफ़",
        "autostart": "बूट पर शुरू",
        "tray_show": "दिखाएं",
        "tray_start": "शुरू",
        "tray_stop": "बंद",
        "tray_quit": "बाहर",
        "close_confirm": "बायपास चल रहा है। बंद करें?",
        "already_running": "HenkerDPI पहले से चल रहा है!",
        "admin_required": "एडमिन अधिकार चाहिए!\nराइट क्लिक > एडमिन के रूप में चलाएं",
        "autostart_added": "[+] स्टार्टअप में जोड़ा गया",
        "autostart_removed": "[-] स्टार्टअप से हटाया गया",
        "engine_active": "[+] HenkerDPI V2 सक्रिय",
        "engine_stopped": "[-] रुका हुआ",
        "uptime_fmt": "{h}घं {m}मि",
        "uptime_fmt_short": "{m}मि {s}से",
        "log_block": "ब्लॉक",
        "custom_domains": "कस्टम डोमेन",
        "add_domain": "जोड़ें",
        "remove_domain": "हटाएं",
        "domain_placeholder": "जैसे: youtube.com",
        "domain_added": "[+] डोमेन जोड़ा: {domain}",
        "domain_removed": "[-] डोमेन हटाया: {domain}",
        "domain_exists": "[!] डोमेन पहले से है: {domain}",
        "domain_invalid": "[!] अमान्य डोमेन",
        "mode_all": "सभी साइट",
        "mode_selective": "चुनिंदा",
        "mode_label": "बायपास मोड",
        "categories": "श्रेणियां",
        "doh_label": "सुरक्षित DNS",
        "doh_desc": "DNS-over-HTTPS से DNS अवरोध हटाएं",
    },
    "ja": {
        "name": "日本語",
        "badge_offline": "  オフライン  ",
        "badge_online": "  オンライン  ",
        "status_off": "バイパス停止中",
        "status_on": "保護有効",
        "desc_off": "ボタンを押して開始",
        "desc_on": "DPIバイパス稼働中 — 全通信を保護",
        "stat_bypass": "バイパス",
        "stat_passed": "通過",
        "stat_uptime": "稼働時間",
        "info_method": "方法",
        "info_fragment": "Fragment",
        "log": "ログ",
        "clear": "クリア",
        "autostart": "起動時に開始",
        "tray_show": "表示",
        "tray_start": "開始",
        "tray_stop": "停止",
        "tray_quit": "終了",
        "close_confirm": "バイパス稼働中です。停止しますか？",
        "already_running": "HenkerDPIは既に稼働中です！",
        "admin_required": "管理者権限が必要です！\n右クリック > 管理者として実行",
        "autostart_added": "[+] スタートアップに追加",
        "autostart_removed": "[-] スタートアップから削除",
        "engine_active": "[+] HenkerDPI V2 有効",
        "engine_stopped": "[-] 停止済み",
        "uptime_fmt": "{h}時間{m}分",
        "uptime_fmt_short": "{m}分{s}秒",
        "log_block": "ブロック",
        "custom_domains": "カスタムドメイン",
        "add_domain": "追加",
        "remove_domain": "削除",
        "domain_placeholder": "例: youtube.com",
        "domain_added": "[+] ドメイン追加: {domain}",
        "domain_removed": "[-] ドメイン削除: {domain}",
        "domain_exists": "[!] ドメインは既にあります: {domain}",
        "domain_invalid": "[!] 無効なドメイン",
        "mode_all": "全サイト",
        "mode_selective": "選択式",
        "mode_label": "バイパスモード",
        "categories": "カテゴリ",
        "doh_label": "セキュアDNS",
        "doh_desc": "DNS-over-HTTPSでDNSブロックを回避",
    },
    "zh": {
        "name": "中文",
        "badge_offline": "  离线  ",
        "badge_online": "  在线  ",
        "status_off": "旁路关闭",
        "status_on": "保护已启动",
        "desc_off": "点击按钮启动",
        "desc_on": "DPI旁路运行中 — 所有流量受保护",
        "stat_bypass": "旁路",
        "stat_passed": "通过",
        "stat_uptime": "时间",
        "info_method": "方法",
        "info_fragment": "Fragment",
        "log": "日志",
        "clear": "清除",
        "autostart": "开机启动",
        "tray_show": "显示",
        "tray_start": "启动",
        "tray_stop": "停止",
        "tray_quit": "退出",
        "close_confirm": "旁路运行中，关闭吗？",
        "already_running": "HenkerDPI已经在运行！",
        "admin_required": "需要管理员权限！\n右键 > 以管理员身份运行",
        "autostart_added": "[+] 已添加到启动",
        "autostart_removed": "[-] 已从启动移除",
        "engine_active": "[+] HenkerDPI V2已启动",
        "engine_stopped": "[-] 已停止",
        "uptime_fmt": "{h}时{m}分",
        "uptime_fmt_short": "{m}分{s}秒",
        "log_block": "拦截",
        "custom_domains": "自定义域名",
        "add_domain": "添加",
        "remove_domain": "删除",
        "domain_placeholder": "例如: youtube.com",
        "domain_added": "[+] 域名已添加: {domain}",
        "domain_removed": "[-] 域名已删除: {domain}",
        "domain_exists": "[!] 域名已存在: {domain}",
        "domain_invalid": "[!] 无效域名",
        "mode_all": "全部网站",
        "mode_selective": "选择性",
        "mode_label": "旁路模式",
        "categories": "类别",
        "doh_label": "安全DNS",
        "doh_desc": "通过DNS-over-HTTPS绕过DNS封锁",
    },
    "ru": {
        "name": "Русский",
        "badge_offline": "  Офлайн  ",
        "badge_online": "  Онлайн  ",
        "status_off": "Обход выключен",
        "status_on": "Защита активна",
        "desc_off": "Нажмите кнопку для запуска",
        "desc_on": "DPI обход работает — весь трафик защищён",
        "stat_bypass": "Обход",
        "stat_passed": "Пропущ.",
        "stat_uptime": "Время",
        "info_method": "Метод",
        "info_fragment": "Fragment",
        "log": "Журнал",
        "clear": "Очистить",
        "autostart": "Автозапуск",
        "tray_show": "Показать",
        "tray_start": "Запустить",
        "tray_stop": "Остановить",
        "tray_quit": "Выход",
        "close_confirm": "Обход работает. Остановить?",
        "already_running": "HenkerDPI уже запущен!",
        "admin_required": "Нужны права администратора!\nПКМ > Запустить от имени администратора",
        "autostart_added": "[+] Добавлено в автозагрузку",
        "autostart_removed": "[-] Удалено из автозагрузки",
        "engine_active": "[+] HenkerDPI V2 активен",
        "engine_stopped": "[-] Остановлен",
        "uptime_fmt": "{h}ч {m}мин",
        "uptime_fmt_short": "{m}мин {s}сек",
        "log_block": "Блок.",
        "custom_domains": "Свои домены",
        "add_domain": "Добавить",
        "remove_domain": "Удалить",
        "domain_placeholder": "напр.: youtube.com",
        "domain_added": "[+] Домен добавлен: {domain}",
        "domain_removed": "[-] Домен удалён: {domain}",
        "domain_exists": "[!] Домен уже в списке: {domain}",
        "domain_invalid": "[!] Неверный домен",
        "mode_all": "Все сайты",
        "mode_selective": "Выборочно",
        "mode_label": "Режим обхода",
        "categories": "Категории",
        "doh_label": "Безопасный DNS",
        "doh_desc": "DNS-over-HTTPS для обхода DNS-блокировок",
    },
    "de": {
        "name": "Deutsch",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Aus",
        "status_on": "Schutz Aktiv",
        "desc_off": "Klicken Sie zum Starten",
        "desc_on": "DPI Bypass läuft — gesamter Verkehr geschützt",
        "stat_bypass": "Bypass",
        "stat_passed": "Durchgel.",
        "stat_uptime": "Laufzeit",
        "info_method": "Methode",
        "info_fragment": "Fragment",
        "log": "Protokoll",
        "clear": "Löschen",
        "autostart": "Autostart",
        "tray_show": "Anzeigen",
        "tray_start": "Starten",
        "tray_stop": "Stoppen",
        "tray_quit": "Beenden",
        "close_confirm": "Bypass läuft. Beenden?",
        "already_running": "HenkerDPI läuft bereits!",
        "admin_required": "Adminrechte erforderlich!\nRechtsklick > Als Admin ausführen",
        "autostart_added": "[+] Zum Autostart hinzugefügt",
        "autostart_removed": "[-] Vom Autostart entfernt",
        "engine_active": "[+] HenkerDPI V2 aktiv",
        "engine_stopped": "[-] Gestoppt",
        "uptime_fmt": "{h}Std {m}Min",
        "uptime_fmt_short": "{m}Min {s}Sek",
        "log_block": "Blockiert",
        "custom_domains": "Eigene Domains",
        "add_domain": "Hinzufügen",
        "remove_domain": "Entfernen",
        "domain_placeholder": "z.B.: youtube.com",
        "domain_added": "[+] Domain hinzugefügt: {domain}",
        "domain_removed": "[-] Domain entfernt: {domain}",
        "domain_exists": "[!] Domain bereits vorhanden: {domain}",
        "domain_invalid": "[!] Ungültige Domain",
        "mode_all": "Alle Seiten",
        "mode_selective": "Selektiv",
        "mode_label": "Bypass-Modus",
        "categories": "Kategorien",
        "doh_label": "Sicheres DNS",
        "doh_desc": "DNS-Sperren mit DNS-over-HTTPS umgehen",
    },
    "da": {
        "name": "Dansk",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Slukket",
        "status_on": "Beskyttelse Aktiv",
        "desc_off": "Klik på knappen for at starte",
        "desc_on": "DPI bypass kører — al trafik beskyttet",
        "stat_bypass": "Bypass",
        "stat_passed": "Passeret",
        "stat_uptime": "Oppetid",
        "info_method": "Metode",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Ryd",
        "autostart": "Start ved opstart",
        "tray_show": "Vis",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Afslut",
        "close_confirm": "Bypass kører. Luk?",
        "already_running": "HenkerDPI kører allerede!",
        "admin_required": "Administratorrettigheder kræves!\nHøjreklik > Kør som administrator",
        "autostart_added": "[+] Tilføjet til opstart",
        "autostart_removed": "[-] Fjernet fra opstart",
        "engine_active": "[+] HenkerDPI V2 aktiv",
        "engine_stopped": "[-] Stoppet",
        "uptime_fmt": "{h}t {m}min",
        "uptime_fmt_short": "{m}min {s}sek",
        "log_block": "Blokeret",
        "custom_domains": "Brugerdefinerede domæner",
        "add_domain": "Tilføj",
        "remove_domain": "Fjern",
        "domain_placeholder": "f.eks.: youtube.com",
        "domain_added": "[+] Domæne tilføjet: {domain}",
        "domain_removed": "[-] Domæne fjernet: {domain}",
        "domain_exists": "[!] Domæne findes allerede: {domain}",
        "domain_invalid": "[!] Ugyldigt domæne",
        "mode_all": "Alle sider",
        "mode_selective": "Selektiv",
        "mode_label": "Bypass-tilstand",
        "categories": "Kategorier",
        "doh_label": "Sikker DNS",
        "doh_desc": "Omgå DNS-blokering med DNS-over-HTTPS",
    },
}

DEFAULT_LANG = "tr"


def load_lang_pref() -> str:
    try:
        with open(LANG_FILE, "r") as f:
            data = json.load(f)
            lang = data.get("lang", DEFAULT_LANG)
            if lang in LANGUAGES:
                return lang
    except Exception:
        pass
    return DEFAULT_LANG


def save_lang_pref(lang: str):
    with open(LANG_FILE, "w") as f:
        json.dump({"lang": lang}, f)


def t(key: str, lang: str = None, **kwargs) -> str:
    if lang is None:
        lang = load_lang_pref()
    text = LANGUAGES.get(lang, LANGUAGES[DEFAULT_LANG]).get(key, key)
    if kwargs:
        text = text.format(**kwargs)
    return text
