"""
HenkerDPI V2 - Language Support
8 languages. General-purpose DPI bypass.
"""

import json
import os
import sys

# PyInstaller onefile: __file__ resolves inside the ephemeral _MEIxxxx temp dir
# that Windows deletes on process exit, so the preference must be written next
# to the exe (mirroring config.py) — otherwise the UI language silently resets
# to English on every launch of the frozen build.
if getattr(sys, "frozen", False):
    LANG_DIR = os.path.dirname(sys.executable)
else:
    LANG_DIR = os.path.dirname(os.path.abspath(__file__))
LANG_FILE = os.path.join(LANG_DIR, "lang_pref.json")

LANGUAGES = {
    "tr": {
        "name": "Turkce",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Kapali",
        "status_on": "Koruma Aktif",
        "desc_off": "Baslatmak icin butona tiklayin",
        "desc_on": "DPI bypass calisiyor",
        "stat_bypass": "Bypass",
        "stat_passed": "Gecen",
        "stat_uptime": "Sure",
        "info_method": "Yontem",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Temizle",
        "autostart": "Acilista baslat",
        "tray_show": "Goster",
        "tray_start": "Baslat",
        "tray_stop": "Durdur",
        "tray_quit": "Cikis",
        "close_confirm": "Bypass calisiyor. Kapatilsin mi?",
        "already_running": "HenkerDPI zaten calisiyor!",
        "admin_required": "Yonetici yetkisi gerekli!\nSag tik > Yonetici olarak calistir",
        "autostart_added": "[+] Acilisa eklendi",
        "autostart_removed": "[-] Acilistan kaldirildi",
        "engine_active": "[+] HenkerDPI V2 aktif",
        "engine_stopped": "[-] Durduruldu",
        "uptime_fmt": "{h}s {m}dk",
        "uptime_fmt_short": "{m}dk {s}sn",
        "log_block": "Engel",
        "custom_domains": "Ozel Domainler",
        "add_domain": "Ekle",
        "remove_domain": "Sil",
        "domain_placeholder": "orn: youtube.com",
        "domain_added": "[+] Domain eklendi: {domain}",
        "domain_removed": "[-] Domain silindi: {domain}",
        "domain_exists": "[!] Domain zaten listede: {domain}",
        "domain_invalid": "[!] Gecersiz domain",
        "mode_all": "Tumu",
        "mode_selective": "Secili",
        "mode_label": "Bypass Modu",
        "categories": "Kategoriler",
        "doh_label": "Guvenli DNS",
        "doh_desc": "DNS-over-HTTPS ile DNS engellemesini as",
    },
    "en": {
        "name": "English",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running — all traffic protected",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close it?",
        "already_running": "HenkerDPI is already running!",
        "admin_required": "Admin privileges required!\nRight click > Run as administrator",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "engine_active": "[+] HenkerDPI V2 active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Bypass DNS blocking with DNS-over-HTTPS",
    },
    "hi": {
        "name": "Hindi",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Start button press kare",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!\nRight click > Run as administrator",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "engine_active": "[+] HenkerDPI V2 active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Bypass DNS blocking with DNS-over-HTTPS",
    },
    "ja": {
        "name": "Japanese",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "engine_active": "[+] HenkerDPI V2 active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Bypass DNS blocking with DoH",
    },
    "zh": {
        "name": "Chinese",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "engine_active": "[+] HenkerDPI V2 active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Bypass DNS blocking with DoH",
    },
    "ru": {
        "name": "Russian",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Autostart",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "engine_active": "[+] HenkerDPI V2 active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Bypass DNS blocking with DoH",
    },
    "de": {
        "name": "Deutsch",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Aus",
        "status_on": "Schutz Aktiv",
        "desc_off": "Klicken Sie zum Starten",
        "desc_on": "DPI Bypass aktiv",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Methode",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Autostart",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "engine_active": "[+] HenkerDPI V2 active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Bypass DNS blocking with DoH",
    },
    "da": {
        "name": "Dansk",
        "badge_offline": "  Offline  ",
        "badge_online": "  Online  ",
        "status_off": "Bypass Off",
        "status_on": "Protection Active",
        "desc_off": "Click the button to start",
        "desc_on": "DPI bypass running",
        "stat_bypass": "Bypass",
        "stat_passed": "Passed",
        "stat_uptime": "Uptime",
        "info_method": "Method",
        "info_fragment": "Fragment",
        "log": "Log",
        "clear": "Clear",
        "autostart": "Start on boot",
        "tray_show": "Show",
        "tray_start": "Start",
        "tray_stop": "Stop",
        "tray_quit": "Quit",
        "close_confirm": "Bypass is running. Close?",
        "already_running": "HenkerDPI already running!",
        "admin_required": "Admin privileges required!",
        "autostart_added": "[+] Added to startup",
        "autostart_removed": "[-] Removed from startup",
        "engine_active": "[+] HenkerDPI V2 active",
        "engine_stopped": "[-] Stopped",
        "uptime_fmt": "{h}h {m}m",
        "uptime_fmt_short": "{m}m {s}s",
        "log_block": "Blocks",
        "custom_domains": "Custom Domains",
        "add_domain": "Add",
        "remove_domain": "Remove",
        "domain_placeholder": "e.g. youtube.com",
        "domain_added": "[+] Domain added: {domain}",
        "domain_removed": "[-] Domain removed: {domain}",
        "domain_exists": "[!] Domain already listed: {domain}",
        "domain_invalid": "[!] Invalid domain",
        "mode_all": "All Sites",
        "mode_selective": "Selective",
        "mode_label": "Bypass Mode",
        "categories": "Categories",
        "doh_label": "Secure DNS",
        "doh_desc": "Bypass DNS blocking with DoH",
    },
}

DEFAULT_LANG = "en"


def load_lang_pref() -> str:
    try:
        with open(LANG_FILE, "r") as f:
            data = json.load(f)
            lang = data.get("lang", DEFAULT_LANG)
            if lang in LANGUAGES:
                return lang
    except Exception:
        pass
    return DEFAULT_LANG


def save_lang_pref(lang: str):
    with open(LANG_FILE, "w") as f:
        json.dump({"lang": lang}, f)


def t(key: str, lang: str = None, **kwargs) -> str:
    if lang is None:
        lang = load_lang_pref()
    text = LANGUAGES.get(lang, LANGUAGES[DEFAULT_LANG]).get(key, key)
    if kwargs:
        text = text.format(**kwargs)
    return text
